### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by maximegodard** [decidim-ice/decidim-module-decidim_awesome#178]
Install does not work on decidim 0.25

1. Add in Gemfile 'gem "decidim-decidim_awesome"'
2. Exec bundle -> OK
3. Exec "bundle exec rails decidim_decidim_awesome:install:migrations" 
4. Get the error : NoMethodError: undefined method `register_assets_path' for Decidim:Module !

 -Ubuntu 18.04

**Comment by microstudi** [comment]
closing as deprecated
